### ISSUE TITLE
Unable to change permissions

### ISSUE THREAD

**Issue by RenaKunisaki** [TeamAmaze/AmazeFileManager#1054]
Using F-Droid version on LineageOS 15.1 on Essential PH-1.

1. With root access enabled, go to /system/media
2. Select bootanimation.zip and change permissions
3. When pressing Set, the message "done" appears, but permissions aren't changed.

I am able to add, remove, and rename files in this directory.

**Comment by VishalNehra** [comment]
Can you please post a logcat too.

**Comment by chekovma** [comment]
I suspect that Amaze is not actually remounting /system rw when doing a permissions change instead of a file operation.  The code for copy, rename, delete, move etc in RootUtils.java explicitly calls mountFileSystemRW(destinationPath) before executing but I couldn't find (only looked a bit) code that would do the same for a chmod.

**Comment by pyrocks** [comment]
I hit the exact same problem on LineageOS 14.1 trying to change permissions on bootanimation.zip

**Comment by VishalNehra** [comment]
````The code for copy, rename, delete, move etc in RootUtils.java explicitly calls mountFileSystemRW(destinationPath) before executing but I couldn't find (only looked a bit) code that would do the same for a chmod.````
Will look into it.
