### ISSUE TITLE
Amaze File Manager : can not extract the file

### ISSUE THREAD

**Issue by evisored** [TeamAmaze/AmazeFileManager#1146]
#### Expected behavior
I hope to extract without error and work properly.

#### Actual behavior
When I want to extract the .rar file I instantly receive the message "error".

#### How to reproduce
Step1. Select the file you want to extract

![step2.jpg](https://cdn.utopian.io/posts/2c682f73d9ec52d188fad91115a238066dc9step2.jpg)

![s3.jpg](https://cdn.utopian.io/posts/ba6e87078ae3c22b09e6d3cef1c57ecabe6es3.jpg)

Nox Emulator Android

![Screenshot_6.jpg](https://cdn.utopian.io/posts/f4737e78d6055bbd251c074caba57923299cScreenshot_6.jpg)

Version APP

![Screenshot_5.jpg](https://cdn.utopian.io/posts/69bcd400fc143143fa3d94f456bbb5362600Screenshot_5.jpg)

# **Material**

1. NoxPlayer 5.0.0.1 version download –> [link](http://res05.bignox.com/g5/M00/01/77/CqtxtVl7EleAadCwEVE1iBHi4co697.exe?filename=nox_setup_v5.0.0.1_full_intl.exe)

2. Amaze File Manager download –> [link](https://play.google.com/store/apps/details?id=com.amaze.filemanager)

3. File Test Rar –> [link](https://drive.google.com/file/d/1zVxvx7M8K0deG_TDLhKT8aLRnP4D-ZaD/view?usp=sharing)

#### Recording Of The Bug
https://www.youtube.com/watch?v=OHpY2DNhr7Q&feature=youtu.be
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@visored/amaze-file-manager-can-not-extract-the-file">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ManjuKiranM** [comment]
I had the same issue.
Upon debugging I found a way to extract.
1. First change : 
In "src\main\java\com\amaze\filemanager\utils\MainActivityHelper.java" 
There is issue in "public void extractFile(File file)" where call to "decompressor.decompress(file.getPath())" is passing file path instead of the directory path where it should be extracted.
**Fix** : change the call to "decompressor.decompress(file.getParent())"

2. Second change:
In "src\main\java\com\amaze\filemanager\filesystem\compressed\extractcontents\helpers\ZipExtractor.java"
in function "extractEntry" there is a if condition to check CanonicalPath 
"if (!outputFile.getCanonicalPath().startsWith(outputDir)) {
      throw new IOException("Incorrect ZipEntry path!");
    }" 
I am not sure why the result is being negated but removing the negation helped me.
**Fix** : if (outputFile.getCanonicalPath().startsWith(outputDir)) {
      throw new IOException("Incorrect ZipEntry path!");
    }

Let me know if I am wrong in any way :)

**Comment by TranceLove** [comment]
Closing for the following reasons:
- OP's screenshots and test RAR file had gone. Sorry that we were not able to look into the problem in time
- Extractor classes had undergone an overhaul, possibly the problem had been fixed

Please feel free to re-open in case you still have problems with current version.
