### ISSUE TITLE
"Open as..." dialog after 'creating' a bookmark on API 15

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1159]
Testing with what seems to be my everything-that-could-possibly-break-breaks phone, when a bookmark is selected in the drawer, the app supposedly 'creates' a new folder ("Bookmark not found creating new folder" toast) and shows the "open as..." dialog, as if what was created were a file.

**Comment by TranceLove** [comment]
Reproducible with Nexus One emulator running ICS, ARM or x86.

Should be hitting the same problem as #1160, that is a consequence of system denied creating a folder and bookmark in an nonexistent user storage space.

**Comment by TranceLove** [comment]
An update to the issue: it does related to the broken Android emulator implementation, as mentioned [here](https://stackoverflow.com/a/45967319/768633). Basically, downgrade the SDK tools launching the emulator instead of strictly from within Android Studio would fix the storage issue.

So try these to launch the ICS emulator:
1. Download Android SDK tools r25.2.5 ([Windows](http://dl-ssl.google.com/android/repository/tools_r25.2.5-windows.zip), [Linux](http://dl-ssl.google.com/android/repository/tools_r25.2.5-linux.zip), [OSX](http://dl-ssl.google.com/android/repository/tools_r25.2.5-macosx.zip))
2. Extract under `$ANDROID_SDK_ROOT`. Of course you'll want to use a different name for the folder, like `tools-r25`, to prevent conflict/overwriting
3. Inside `$ANDROID_SDK_ROOT/tools-r25`, run the emulator using command line

`./emulator -avd Nexus_One_API_15`

You should see the emulator correctly mount and prepare the SD card partition, and create file would work (using current `master`).

I'll mark this as invalid and close. Reopen this should any problems arise even with the above workaround, or with a physical device.
