### ISSUE TITLE
Secure FTP IP starts with "sftp://" instead of "ftps://"

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1300]
Secure FTP IP starts with "sftp://" instead of "ftps://", the first one is:
> FTP over SSH is the practice of tunneling a normal FTP session over a Secure Shell connection.

And "ftps://" stands for:

> FTPS (also known as FTPES, FTP-SSL, and FTP Secure) is an extension to the commonly used File Transfer Protocol (FTP) that adds support for the Transport Layer Security (TLS) and the Secure Sockets Layer (SSL) cryptographic protocols.

I think we are showing to the user the wrong protocol as being used. But then again, I don't know much of networking protocols.

**Comment by VishalNehra** [comment]
We're creating a sftp server.. not ftps.

**Comment by EmmanuelMess** [comment]
@TranceLove was called "Fix for enabling SSL for FTP server" and FileZilla tells me to put "ftps://" in front of the host to connect via implicit SSL, that's why I thought that we were using SSL...

**Comment by TranceLove** [comment]
However, I'll agree changing the URL prefix to `ftps`, since `sftp://` seems to be generally regarded as related to SSH/SCP, at least in the case of Nautilus (GNOME)/Nemo (Cinnamon).

Actually, FTP with implicit SSL does not even have a S in the URL prefix - that `ftps://` is usually regarded as URL prefix of FTP with __explicit__ SSL; but if you would like, it's OK to use `ftps://` here, for user to recognize the need to enabling SSL connection when setting things up in Filezilla.
