### ISSUE TITLE
Add dual pane option and bug report

### ISSUE THREAD

**Issue by MrNerd18** [TeamAmaze/AmazeFileManager#1375]
Hi! Would it be possible to add dual panel option? It would be useful for copying files etc.

Also I have noticed bug. When you are trying to remove file somewhere in root directory (with root access) and you don't have permissions to file, Amaze will "freeze" (showing just gray background with all files disappeared).

**Comment by EmmanuelMess** [comment]
There are two workspaces, swipe left or right in the file list to move to the other one.

Thanks for the bug report.

**Comment by VishalNehra** [comment]
> and you don't have permissions to file

What do you mean? Root user have all the permissions. If you gave root access, the file should be deleted, simple as that. If you're unable to do that on latest beta v3.3.0RC1 we will open it (test and report). I tested file deletion positive with proper root permissions given to Amaze.

**Comment by Attedz** [comment]
No, if you have root permissions you don't have access to all files/folders. For example:
Let's say we have file called "Delete" in /oem directory. You have root access provided with Magisk.
But the file "Delete" have read only permissions. You are going to delete that file with Amaze without changing permissions to read write. But when you are trying to delete it Amaze will freeze because you don't have write permissions. Instead of freezing it should notify "Permissions denied".

**Comment by VishalNehra** [comment]
Don't worry about that, we do [modify the permissions to rw](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/main/java/com/amaze/filemanager/utils/RootUtils.java#L147) before deleting the file.
Please confirm if you're facing this bug with v3.3.0RC1 on beta channel of play store, because I can delete files just fine.

**Comment by Attedz** [comment]
Beta is working.
