### ISSUE TITLE
Storage analysis for deleting useless files like Files GO app

### ISSUE THREAD

**Issue by arpitkh96** [TeamAmaze/AmazeFileManager#1392]
Hey guys, I am thinking of implementing some features like 'Files Go' to detect useless files but in a different way. Like Go app simply show all the images of Whatsapp folder. I am thinking of using deep learning to detect and separate out memes, portraits and documents, so that managing them can be easy.

Any suggestions are highly appreciated.

**Comment by arpitkh96** [comment]
https://play.google.com/store/apps/details?id=com.tecomen.android.objectdetector
Try this.. This works on my phone with less than 1s delay and absolutely no lag or anything.. There are models now  of size 10 mb with equivalent performance

**Comment by EmmanuelMess** [comment]
Some questions:
How many photos would we need to parse per second?
Where do we train the model?
How will make and maintain the model and AI training code? This doesn't seem cheap (timewise) to make.

**Comment by arpitkh96** [comment]
That detector detects 80 classes and is much more complex..we can fit in smaller... perhaps in a separate plugin..
About training, I have GPU . I know it can be slow to run on phone.. But we will only find out when we try right

**Comment by TranceLove** [comment]
Really cool idea, but I prefer this feature be available as an separate add-on rather than built into Amaze too, for the reasons that

- as an end user I don't like a little file manager weighs more than 5MB, and I'll prefer have an option of taking care of the files on my device on my own completely
- as one of the developers of Amaze I'm worried about the overhead introduced by integrating the learner into the app, though in reality integrating analytics into an app usually results in scattering calls like log messages everywhere🙄

**Comment by EmmanuelMess** [comment]
> learner into the app

To learn what? Only detection, no learning in the app.

**Comment by LeMeteorique** [comment]
Hi, I have a suggestion, How about a feature that deletes Apps cache? It helps reducing unnecessary storage when it needed by the user.

**Comment by EmmanuelMess** [comment]
@LeMeteorique First, remember to open new issues for features, unless the same feature has already an issue. Second, I think we can't delete other app's cache. Third, that doesn't see like something an file manager should do, IMO.

**Comment by VishalNehra** [comment]
This has been done in [Amaze File Utilities](https://play.google.com/store/apps/details?id=com.amaze.fileutilities&hl=en_IN&gl=US)
