### ISSUE TITLE
Unable to add cloud connections

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1394]
@EmmanuelMess please try to minimize much code refactoring. It's causing unwanted introduction of bugs. 
I'm unable to add any cloud connection. As soon as i authenticate and return back to Amaze, it re-initiates the authentication. 
I can't say where this bug was introduced.

**Comment by EmmanuelMess** [comment]
Sorry, I'll git-bisect.

**Comment by EmmanuelMess** [comment]
Allow me a rant.

> @EmmanuelMess please try to minimize much code refactoring.

I don't think I have ever touched the code that deals with the cloud addition, something I did might have broken it as a side effect. 
With that said, when bisecting (from 2d7e101) it seemed that (A) the deletion of cloud connections was not working or (B) the addition of cloud connections was probabilistic (a connection was being added 0 to 3 times). 
So I turn to checking the code, `MainActivity.addConnection()` adds a connection, calls `CloudHandler.findEntry()`:
https://github.com/TeamAmaze/AmazeFileManager/blob/ac1b080a19da389904cbd2c96f9c7fa1445b27e4/app/src/main/java/com/amaze/filemanager/database/CloudHandler.java#L141-L168

* `serviceType` is an `OpenMode`, any change to add elements to the `OpenMode` could subtly break `serviceType.ordinal()`.
* Why is the `serviceType.ordinal()` passed between " " in the query? 
```
try {
    cloudEntry.setPersistData(CryptUtil.decryptPassword(context, cursor.getString(2)));
} catch (Exception e) {
    e.printStackTrace();
    cloudEntry.setPersistData("");
    return cloudEntry;
}
```
* What `Exception` would it catch? No idea, but it certainly would fail safely and the function user would know that now `persistData` is `""`, not even `null`, just empty string.

Going back to `MainActivity.addConnection()`:

https://github.com/TeamAmaze/AmazeFileManager/blob/ac1b080a19da389904cbd2c96f9c7fa1445b27e4/app/src/main/java/com/amaze/filemanager/activities/MainActivity.java#L1793-L1820

* The result of `CloudHandler.findEntry()` is compared to `null`, for what did I need the `CloudEntry` returned? Nothing, I'm sure an sqlite query that returns only TRUE or FALSE could have been used.
* Get a loader's callbacks, where? `MainActivity`, because there aren't enough things there already.

A loader is created:

https://github.com/TeamAmaze/AmazeFileManager/blob/ac1b080a19da389904cbd2c96f9c7fa1445b27e4/app/src/main/java/com/amaze/filemanager/activities/MainActivity.java#L1830-L1902

* Let's start by killing a never set `AsyncTask`?
* Instead of having two different async callback in two different files, we have a switch.
```
List<CloudEntry> cloudEntries = cloudHandler.getAllEntries();

// we want keys for services saved in database, and the cloudrail app key which
// is at index 1
String ids[] = new String[cloudEntries.size() + 1];

ids[0] = 1 + "";
for (int i=1; i<=cloudEntries.size(); i++) {

    // we need to get only those cloud details which user wants
    switch (cloudEntries.get(i-1).getServiceType()) {
        case GDRIVE:
            ids[i] = 2 + "";
            break;
        case DROPBOX:
            ids[i] = 3 + "";
            break;
        case BOX:
            ids[i] = 4 + "";
            break;
        case ONEDRIVE:
            ids[i] = 5 + "";
            break;
    }
}
```
* That doesn't seem right, for one, `ids`' type is String[]; `ids[0] = 1 + "";` with no explanation; and there are a lot of harcoded literals, instead of constants.
* `default: return null`, on a method that should return a `@NonNull Loader<Cursor>` to be executed.

Then `onLoadFinished()`:
https://github.com/TeamAmaze/AmazeFileManager/blob/ac1b080a19da389904cbd2c96f9c7fa1445b27e4/app/src/main/java/com/amaze/filemanager/activities/MainActivity.java#L1904-L2139
* 239 lines? `AsyncTask` included. It also seems it has *some* lines more than once, that could be extracted into functions. Not reading this, not now at least.

**Comment by EmmanuelMess** [comment]
It seems that `onLoadFinished()` is getting called after each resume, maybe destroy the loader when the operation is finished?

**Comment by VishalNehra** [comment]
My bad, assigning you to a code that depends proprietary plugin which is closed. 
> I don't think I have ever touched the code that deals with the cloud addition, something I did might have broken it as a side effect.

This is what I meant. Never meant to say you made changes in cloud code and broke it.

**Comment by EmmanuelMess** [comment]
> My bad, assigning you to a code that depends proprietary plugin which is closed.

I don't mind fixing the plugin, I just wanted to say that the code quality can be higher.

-----------------------------------------
[This](https://gist.github.com/EmmanuelMess/8aabccfc7e3c213b33f03873d58d8cef) patch seems to fix the problem for me, please test it's not just for me.
