### ISSUE TITLE
Not Found on Google Play

### ISSUE THREAD

**Issue by BMitrovic17** [TeamAmaze/AmazeFileManager#1443]
Clicking on the link in the readme that goes to google play i get "We're sorry, the requested URL was not found on this server."
Searching for "Amaze File Manager" yields no results either.

Any reason why it was removed from the play store ?

**Comment by VishalNehra** [comment]
Meh, long story short, we introduced Google payments subscription API to accept donations long back worth $1.
And one user actually subscribed to it. But after some time we removed it from Amaze, now accepting donations through individual Paypal accounts. But since that subscription was made, Play Store still reflected that Amaze had in-app purchases.
Now it seems Google has updated their payments policy and as per new policy

> Developers must not mislead users about the apps they are selling nor about any in-app services, goods, content, or functionality offered for purchase. If your product description on Google Play refers to in-app features that may require a specific or additional charge, your description must clearly notify users that payment is required to access those features.

Our description never had any such info. as we are not using the API in the first place.

**Comment by EmmanuelMess** [comment]
@VishalNehra this should have been disclosed earlier

**Comment by VishalNehra** [comment]
I've resubmitted Amaze with necessary changes required in the listing description.

**Comment by EmmanuelMess** [comment]
Do update this issue with news.

**Comment by VishalNehra** [comment]
We're up on play store.

**Comment by IvanFon** [comment]
The link in the readme isn’t working, and the only thing I can find in the Play Store is [this](https://play.google.com/store/apps/details?id=com.cogzidel.file), which looks a little bit sketchy. If that actually is the official listing, it would probably help if a description were added.

**Comment by EmmanuelMess** [comment]
@VishalNehra we're down again

**Comment by VishalNehra** [comment]
We're up, this time for good.

**Comment by dm4uz3** [comment]
and now it's down again
