### ISSUE TITLE
Shortcut creation malformed, leads to crash

### ISSUE THREAD

**Issue by yxo-6o6uka** [TeamAmaze/AmazeFileManager#1527]
This is a regression in 3.3.
Repro:

Occurs on 3 Samsung devices running Android 7.1, 8.0 and 8.1

Settings>Shortcuts>Add Item
Enter  Name and valid directory path, then Create.

The shortcut Name and Directory fields are transposed, leading to simple name used as directory path. It visible in created shortcut. Subsequent tap on this shortcut cases crash.

Workaround is to edit the malformed shortcut transposing name and Directory, save the change. It saved correctly in edit dialog.

**Comment by 0xACE** [comment]
I'm running v3.3.2 and confirm this... The app is a crashfest...

Another funny one is to create a new shortcut and leave the shortcut without a set "name" and then you can't open Amaze anymore because the corrupt settings will cause the app to crash immediately.

At first I thought: "oh shit, I'll have to reset the config", but then I found this solution instead:
System Settings > Apps > Amaze > App settings > Disable shortcuts > Start amaze app as normal > reconfigure the shortcuts
