### ISSUE TITLE
"Paste" option seems to be missing?

### ISSUE THREAD

**Issue by kevjonesin** [TeamAmaze/AmazeFileManager#1637]
When I select a folder I get 'copy', 'trash', and 'cut' icons up top and 'menu dots' bring up copy and cut options, but I'm not offered any paste option? Even when I've previously tapped copy/cut for a selected file (via either icon or menu).

Am running Amaze v.3.3.2 on a Galaxy S7 Edge running the Samsung version of Oreo.

**Comment by VishalNehra** [comment]
Sorry for getting late reply here... please give a screenshot after you press on copy on any item, and we'll give this a high priority.

**Comment by WildPenquin** [comment]
I can confirm this issue, I can not move or copy files anymore - paste option is missing. This is on OP3T, latest official OTA.

**Comment by kevjonesin** [comment]
Thanks @WildPenguin, I scrolled as suggested and have now found a 'clipboard' paste icon and have confirmed that it works.

**Comment by tdbe** [comment]
This is very bad UX and I have a product design degree.. There is absolutely no way to know that there is a hidden top bar. There are no hints that there ever was a top bar that autohides. You need to either show a bar, then have an animation that auto hides the bar, either have an icon or a visual indicator that there is such a thing in your app. And also add the paste button in the context menus of folders next to copy and cut...!

This app is amazing otherwise. Simple, open source, powerful, customizable. This paste thing is the only unexpectedly dumb thing.

**Comment by VishalNehra** [comment]
> In 2021, there is a top search engine recommendation, even in duckduckgo, when you put in Amaze File Manager -- it autocompletes with HOW TO PASTE.
> 
> This is very bad UX and I have a product design degree.. There is absolutely no way to know that there is a hidden top bar. There are no hints that there ever was a top bar that autohides. You need to either show a bar, then have an animation that auto hides the bar, either have a down arrow/minimize icon that shows there is an expandable top bar up top. And also add the paste buttons in the context menus of folders next to copy and cut wtf...?
> 
> This app is AMAZING otherwise. Simple, open source, powerful, customizable. This paste thing is the only unexpectedly dumb unfindable thing.

Hi. Thanks for writing. As of 3.6 we just merged a change in design of paste button. I'm attaching a screenshot.. hoping this would actually fix the UX problems. You just gotta wait for the next release.
![Screenshot_20210405-015334](https://user-images.githubusercontent.com/5211568/113520625-ee053200-95b1-11eb-8aca-6e5898549df5.jpg)

**Comment by tdbe** [comment]
Beautiful. Thank you :)
