### ISSUE TITLE
Can't install apks after updating to Android 10

### ISSUE THREAD

**Issue by EliSadaka** [TeamAmaze/AmazeFileManager#1687]
I can no longer install apps from apk files in Amaze after updating to Android 10. When I try to all I get is a toast message that just says "Error". I've checked and Amaze does have permission to install apps. This is on Amaze 3.3.4.

**Comment by tomwiggers** [comment]
I don't think Amaze is the only application with this problem. I suspect it is something related to Android. If I download an APK using my web browser and tap on the downloaded file, it asks with what application I would like to open it with and shows a list instead of starting the package installer. However none of the listed options seem to habe anything to do with installing a package.

**Comment by VishalNehra** [comment]
This might help 
https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/content/InstallApkSessionApi.java

**Comment by EmmanuelMess** [comment]
Related #1718.
