### ISSUE TITLE
Ability to Create Shortcuts?

### ISSUE THREAD

**Issue by EddieBrock** [TeamAmaze/AmazeFileManager#1848]
ES File Explorer (and many others) have the ability to create a Home Screen shortcut to a file.
I would love to see Amaze have this functionality as it's my explorer of choice.

Thanks.

**Comment by TranceLove** [comment]
Current code does support creating shortcuts, but limit to folders only.

To create a file shortcut at home screen, we need
- ability to pass `path` to intent as `content://` URIs (for future compatibility; current passing path alone may crash viewer receiving the `ACTION_VIEW` intent)
- use file thumbnail as icon via Glide. This may imply reusing `RecyclerAdapter.show*Thumbnail*()` methods

**Comment by VishalNehra** [comment]
I'm not in favour of adding files directly on homescreen. This shouldn't be supported by a file manager. A launcher can add support for this. 
I say this because the lifecycle would involve first opening our application then passing it on to 3rd party application. While a launcher can directly open the file from the home screen without opening a middleman.
