### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [TeamAmaze/AmazeFileManager#1870]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by TranceLove** [comment]
Hmmm... this is a hard one.

We chose to use spongycastle since we need to use updated BouncyCastle for updated crypto code not available from stock BouncyCastle, which versions differ with different Android versions.

Happy to know if there is a way to use updated BouncyCastle without letting Android apps ignore the version we want to use, but always fall back to Android's own BouncyCastle.

**Comment by Neustradamus** [comment]
@TranceLove: Thanks for your comment!
Currently Bouncy Castle last version is 1.65 and Spongy Castle last version is 1.58.
Spongy Castle is a fork of Bouncy Castle.
Please look previous links :)

Since several years, a lot of projects have already moved from Spongy Castle to Bouncy Castle because the project is dead.

You can see discussion "34" in https://github.com/rtyley/spongycastle/issues.

**Comment by TranceLove** [comment]
Thanks @Neustradamus, [@rtyley/spongycastle#34](https://github.com/rtyley/spongycastle/issues/34) and a quick Google/StackOverflow both pointed to a node.js module to help building bouncycastle at their own namespace: [@jbuhacoff/nodejs-mybc-util](https://github.com/jbuhacoff/nodejs-mybc-util)

Let's see when I have time to make our own bouncycastle jars.

**Comment by Neustradamus** [comment]
@TranceLove: nodejs-mybc-util is optional because a lot of projects have been migrated without...

**Comment by Neustradamus** [comment]
@TranceLove: Not possible to add directly in gradle?

**Comment by TranceLove** [comment]
> @TranceLove: Not possible to add directly in gradle?

Sorry for overlooking - that [the discussion mentioned above](https://github.com/rtyley/spongycastle/issues/34) actually pointed out that there is no namespace collusion problem since Android 3.0.

I then tried a bit, seems promising. But is getting Espresso test failures on Kitkat - seems not directly related to migration to BouncyCastle though.

Will retract #1874 after tests passed.

**Comment by VishalNehra** [comment]
Great, thanks for looking into this @TranceLove

**Comment by Neustradamus** [comment]
@TranceLove, @VishalNehra, @bowiechen: Thanks a lot!
But not complete: https://github.com/TeamAmaze/AmazeFileManager/search?q=spongycastle&unscoped_q=spongycastle
