### ISSUE TITLE
Connecting to SMB: Outdated Protocol, Silent Error

### ISSUE THREAD

**Issue by Shizcow** [TeamAmaze/AmazeFileManager#1960]
## Description
When connecting to a SMB server which has a modern protocol accepted, Amaze silently fails, showing the loading icon forever.

## To Reproduce
1. Create a samba host server. I'm using the default settings in the arch linux samba packge, which includes a min protocol version of something like SMB2
2. Try to connect

## Expected behavior
Ideally, connection would succeed. Or at least an error message should pop up.

## Diagnosing
I turned on logging for my samba server, to find `no protocol supported`. This means Amaze is trying to connect via an old SMB protocol that's no longer standard (for my distro at least).

## Workaround
On my samba server, I set `min protocol = core`. This causes connection to succeed.

## RFE
Short term: Detect errors in connection. If Amaze is using an incompatible protocol, alert the user.

Long term: Implement short term. Add options for using different SMB protocols during connection.

**Comment by Hackmiester5000** [comment]
I have also see this issue, as we have been required to no longer use the SMB1 protocol as Windows 10 Users can no longer connect to shares using SMB1 since Windows 10 has deprecated it and no longer installs/automatically uninstalls SMB1 protocol support. See this article: [smbv1-not-installed-by-default-in-windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/smbv1-not-installed-by-default-in-windows)

**Comment by VishalNehra** [comment]
We have already migrated to SMBv2
You can opt into beta program and try 3.5 series from Play Store (: 
@Hackmiester5000 
This should be closed @TranceLove  CMIIW

**Comment by Shizcow** [comment]
Oh, cool and good to know. When will this feature hit master? I'm using amaze from fdroid so the beta isn't yet available to me.

**Comment by VishalNehra** [comment]
Definitely, just wait a bit more.. once stable 3.5 is out it'll be on fdroid. Please note we're not on main fdroid, check out our README for link.
