### ISSUE TITLE
Add swipe support to image viewer

### ISSUE THREAD

**Issue by gthvidsten** [TeamAmaze/AmazeFileManager#2091]
When viewing an image in a folder with many images it should be possible to swipe left/right to see the next/previous image in the folder. As it is now you have to click the back button, find the next image, then click this image. Rinse and repeat for all images in the folder.

Samsung Galaxy S7 w/Android 8
Amaze File Manager 3.5.0

**Comment by VishalNehra** [comment]
@gthvidsten I think this depends more on the third party app with which you decide to open your pic than Amaze itself.
If we design an internal image viewer then surely we'll take care of this.

**Comment by gthvidsten** [comment]
Oh, so you're telling me there's no internal image viewer and it actually opens up a different app? That would explain it.
Disappointing that there's no internal image viewer, though. That's the main thing I want to use file managers for and yours was very promising. When you say "if we design"... is there a chance it might be an easy design and could end up in the app quickly? :)

**Comment by EmmanuelMess** [comment]
Probably not

**Comment by Cebtenzzre** [comment]
The lack of this feature is the main reason I cannot use this app instead of [FX File Explorer](https://play.google.com/store/apps/details?id=nextapp.fx) or [File Manager Plus](https://play.google.com/store/apps/details?id=com.alphainventor.filemanager). I wanted to use this app because FX has small thumbnails and File Manager Plus doesn't support tabs.

**Comment by VishalNehra** [comment]
> The lack of this feature is the main reason I cannot use this app instead of [FX File Explorer](https://play.google.com/store/apps/details?id=nextapp.fx) or [File Manager Plus](https://play.google.com/store/apps/details?id=com.alphainventor.filemanager). I wanted to use this app because FX has small thumbnails and File Manager Plus doesn't support tabs. I don't know of any dedicated gallery apps with SFTP support.

You can use our app amaze utilities that has this feature 
https://play.google.com/store/apps/details?id=com.amaze.fileutilities

**Comment by Cebtenzzre** [comment]
@VishalNehra As far as I can tell, Amaze File Utilities does not support SFTP and does not let you open folders in different tabs. Amaze File Manager is much closer to what I am looking for. But I often want to view a few images or videos without switching to a different app or going back to the file manager in between each one.

**Comment by VishalNehra** [comment]
> @VishalNehra As far as I can tell, Amaze File Utilities does not support SFTP and does not let you open folders in different tabs. Amaze File Manager is much closer to what I am looking for. But I often want to view a few images or videos without switching to a different app or going back to the file manager in between each one.

This is how it's designed: 
You install amaze utilities app
Go to a directory that has lots of images using Amaze file manager
Press on either image > select Amaze image viewer from pickup menu
The image viewer opens up and it allows you to view all other images in that directory by swiping left / right without closing and going back and opening another image.
(This is supported only for local files for now).

Let me know if this isn't what you're looking for.

**Comment by Cebtenzzre** [comment]
@VishalNehra After doing a little more setup in Amaze File Utilities I was able to get that working, but it's not quite what I'm looking for. Maybe my use case is kind of specific, but I'm trying to browse a git-annex repository via SFTP. I can't use EasySSHFS because the repo represents files using symbolic links that get lost in translation and disappear. So I've only had success with in-app image viewers.
