### ISSUE TITLE
Failure to decrypt files encrypted with previous phone

### ISSUE THREAD

**Issue by Phenitei** [TeamAmaze/AmazeFileManager#2459]
Dear Team Amaze,

Thank you for your Amaze-ing :wink: work on Amaze ^^ I am having an issue I hope you might be able to help me with. I have extracted from a backup of a previous phone several files that were encrypted with Amaze on Android 7, somewhere around 2019. When I try to decrypt them with my new phone (Android 10, current version of Amaze), instead of asking me for a password, I simply get a toast message saying « Failure to decrypt ». I know the password I used to encrypt the files.

Is there anything I can do to find out more about the reason for the error ?

Thank you!

**Comment by TranceLove** [comment]
You'll also need the app data that contains the information about the encrypted file. If you are able to use backup apps like Titanium, you can safely transfer those app data to your new phone, and that may help you decrypt the file on the new phone.

Although, we don't support "Encrypt on Phone A, decrypt on Phone B" thing officially - this is how I see the issue from the mechanism's perspective, and I only speak for myself but not the team.

**Comment by VishalNehra** [comment]
Yes. Sadly, you can't get them back because the key with which those files were encrypted are kept safe inside the android framework. And no, even with an app data backup/restore you can't transfer the key to new device because of safety concern android doesn't allow this.
Once you changed phone, the key is not there anymore, hence, it doesn't even ask for password.
You can join our telegram channel if you have any more doubts or have any suggestions 
https://t.me/AmazeFileManager

**Comment by Phenitei** [comment]
Welp, that's that then. Thank you for your quick answer!
