### ISSUE TITLE
Cannot use FTP server with hotspot after upgrading to Android 11

### ISSUE THREAD

**Issue by AsyncRes** [TeamAmaze/AmazeFileManager#2720]
**Describe the bug**
On Android 10, I used FTP connection using hotspot to my PC. But after upgrading to Android 11, I can't start FTP server. PC is already connected to my phone hotspot, still it says "connect to a network or enable AP'.  I think it started after android introduces randomized IP (as default gateway of hotspot changes everytime). Also Amaze can't read hotspot IP address. see screenshot below.

Side note: I can however start FTP with Amaze version 3.5.*  (which also shows "no connection" and blank IP address field. it just blindly let me start FTP. Which isnt possible anymore after 3.6.0)

**To Reproduce**
1. connect PC to phone hotspot
2. Go to 'FTP Server' in Amaze.
3. It will prompt an error message.

**Expected behaviour**
It should be able to start FTP with hostpot connection. 

**Screenshots**
<img src="https://user-images.githubusercontent.com/63266908/128557351-33d259fb-acb1-4770-9181-1703f4f82c03.jpg" width="50%"/>

**Smartphone (please complete the following information):**
 - Device: Redmi K30 5G
 - OS: Android 11
 - Rooted: yes
 - Version: 3.6.1

**Additional context**

**Comment by TranceLove** [comment]
Not quite, but perhaps more due to Android 11's restriction on calling internal methods via reflection.

**Comment by TranceLove** [comment]
Made some more investigations, I was wrong. The reflection call didn't block, but I did saw the hotspot's IP address is no longer simply `192.168.43.x` but are anything `192.168.x.y` with /24 netmask.

Will need to think of another way to get this address. Got some clue, still heavy reflection based though.

**Comment by TranceLove** [comment]
The reflection-based solution is not working, due to Android 11 requires system level permission which is impossible for apps to obtain.

A possible and simpler way out without root however, is to use Android's official way to start the hotspot - see [WifiManager#startLocalOnlyHotspot()](https://developer.android.com/reference/android/net/wifi/WifiManager#startLocalOnlyHotspot(android.net.wifi.WifiManager.LocalOnlyHotspotCallback,%20android.os.Handler)) which is available from Android 8.0.

Sounds a long way to go, yes. Sorry for that.

___

Technically speaking, this means

1. `FtpService.getLocalInetAddress()` checks shall be loosened from Android 8
2. Display options changes for the case of no network connection 
a. "Enhanced Toast" or sidebar (or whatever...) as used in copy/cut and paste action shall be used instead of the one currently using. "Open Settings" will still be there, while "Start AP" will be shown for Android >= 8
b. Alternately, we keep the FTP server start/stop button remain clickable, but Amaze will start AP too as FTP server starts. We will ask for user confirmation in this case
3. When pressed "Start AP", invoke `WifiManager#startLocalOnlyHotspot()` above, and from registering a `LocalOnlyHotspotCallback` we can obtain information about the AP's IP address at [LocalOnlyHotspotCallback.onStarted()](https://developer.android.com/reference/android/net/wifi/WifiManager.LocalOnlyHotspotCallback#onStarted(android.net.wifi.WifiManager.LocalOnlyHotspotReservation))
4. When `FtpService` is stopped, AP is automatically stopped too, since it should be no longer used by anyone else

**Comment by NeonOrbit** [comment]
>  Display options changes for the case of no network connection

What about hotspot status, is it possible to obtain? If so, at least should display "Connected" status.

>  Alternately, we keep the FTP server start/stop button remain clickable

This will be life-saver, as we can obtain IP address from PC easily. (This will avoid reconnecting hotspot to PC). Currently start/stop button is not clickable. 

Also how about checking if root is available, and simply obtain the IP address using root, instead of starting new AP.  (This too will avoid the hassle of reconnecting new hotspot).

**Comment by TranceLove** [comment]
> What about hotspot status, is it possible to obtain? If so, at least should display "Connected" status.

I think currently it's still possible, but there are concerns that invoking APIs that are hidden from user code (i.e. through reflection) may be impossible in the future. That's why I think of starting the device's AP from within Amaze, instead of hacking and workarounding with Android's security facilities.

> Also how about checking if root is available, and simply obtain the IP address using root, instead of starting new AP. (This too will avoid the hassle of reconnecting new hotspot).

The "with root" method is simply parsing the output from commands like `ip address` or `ifconfig`, but this also implies the device has one single wifi connection, which is not a good assumption.

On the other hand, current IP address checking should cover non-wifi connections too... so the thing to fix here is this random IP address available after starting the AP on Android >= 11.

**Comment by NeonOrbit** [comment]
> The "with root" method is simply parsing the output from commands like `ip address` or `ifconfig`, but this also implies the device has one single Wi-Fi connection, which is not a good assumption.

But the problem here is only when we use hotspot, not wifi. So it doesn't matter how many wifi connection is established, as Wi-Fi will use wlan0 and Hostpot will use wlan1, also it's not possible to create two hotspot at the same time. 
Here also doesn't matter how many device connected to Hotspot, the IP address of Hotspot itself will be one only. So we can simply get the IP address of Hotspot using `ip route | grep wlan1 | awk '{print $NF}'`  command. (Unless my assumption is wrong?)

**Comment by TranceLove** [comment]
@NeonOrbit Nice thought☺️ Will check.

**Comment by NeonOrbit** [comment]
Thanks, looking forward to it.

**Comment by AsyncRes** [comment]
Any idea when this is going to be fixed? I use this regularly.

**Comment by TranceLove** [comment]
Created #3030 for a more lenient device connectivity check, that eliminate the need to check for AP status, hence allow different IP addresses be used where necessary, without the need of enabling the AP in our code.

We shall see this included in 3.7 cycle.

**Comment by VishalNehra** [comment]
@AsyncRes the build will be generated on our telegram channel, if you want to access it before 3.7 is released (which will take quite some time), you can join our telegram channel at https://t.me/AmazeFileManager
