### ISSUE TITLE
"Grant Permission" prompt appears every time app is opened

### ISSUE THREAD

**Issue by who-is-matt** [TeamAmaze/AmazeFileManager#3215]
**Describe the bug**
Every time I open the app, I am presented with the "Grant Permission" prompt.  Selecting "Grant" results in a "Permission not granted" toast.  Checking the app permissions in the system settings, however, shows that the app has the "Files and media" permission. 

**To Reproduce**
1. Open the app.  The "Grant Permission" prompt appears.
2. Click on "Grant"
3. A "Permission not granted" toast appears at the bottom of the screen.

**Expected behavior**
The "Grant Permission" prompt should not appear if the app already has the "Files and media" permission.  The "Permission not granted" should not appear if the "Grant" action is selected in the "Grant Permission" prompt.

**Screenshots**
![Amaze_20220309_230232](https://user-images.githubusercontent.com/4270243/157593409-d648cd00-c135-45e0-92b2-4b073a018422.png)
![Amaze_20220309_230248](https://user-images.githubusercontent.com/4270243/157593431-96480b5a-b593-4c4d-b91c-99d878c5af84.png)

**Smartphone (please complete the following information):**
 - Device: nVidia Shield TV Pro 2019
 - OS: Android 11
 - Rooted: No
 - Version: 3.6.7

**Additional context**
Uninstalling and re-installing the app doesn't help.  Neither does clearing the cache/data, or manually changing the app permissions in the system settings.

**Comment by VishalNehra** [comment]
This is a strange issue, do you not see a dialog to 'allow' or 'dont allow' after you press the grant button?
I think the issue is, we should two dialogs for permission, in tv it's showing two dialogs but highlighting button in a dialogue behind that has cancel button selected instead. 
Can you try to grant this dialog, and manually go in system settings to allow storage permission?
