### ISSUE TITLE
Feature request: Black theme

### ISSUE THREAD

**Issue by IiroP** [TeamAmaze/AmazeFileManager#336]
For AMOLED

**Comment by phoenix26** [comment]
dark theme is not enough for this? lol

**Comment by rpiotaix** [comment]
No, interesting thig here is that AMOLED screens don't use energy to display black pixels. And dark theme is not 'black'.

**Comment by z751** [comment]
+1

**Comment by bdtoole** [comment]
+1

**Comment by Stuie** [comment]
Chasing that extra few minutes of battery life on a device that you charge every day does not seem like a strong contender for development time compared to some of the more useful features.

I'm not trying to belittle people who want battery life, but I can't imagine you spend so long in your file manager that powering your almost-black pixels is making a significant difference.

**Comment by vishal0071** [comment]
Dropping the idea. It'll add more complexion to code. It I don't think it's worth the time, when you could use all the dark themes in the world (using CMTE/substratum/layers).

**Comment by PiwwowPants** [comment]
The theme management as it is now lends itself to work really well for built in styles but is definitely rough to work with when you add on extra themes.

I put in PR https://github.com/TeamAmaze/AmazeFileManager/pull/864 that handled adding a "Black" theme that really just changes all background colors to solid black instead of the holo dark. Otherwise, it is identical to the dark theme for purposes of contrast and not adding too much technical debt to the app.

**Comment by AeliusSaionji** [comment]
You have two themes, but a third is adding too much code complexity? Custom colors for some interface elements is fine, but custom background color is crossing some line?

Does the dark theme become unusable if the background color is black? That's really all that's needed afaik.

Thanks for submitting a PR Powwow!

**Comment by bowiechen** [comment]
Considering PR #864 is merged, we should close this issue.
