### ISSUE TITLE
Can't open folders with plus ("+") in the name

### ISSUE THREAD

**Issue by infinity0** [TeamAmaze/AmazeFileManager#3560]
**To Reproduce**
1. Create a folder called "a+b".
2. Tap on "a+b". Notice that Amaze tries to open "a b" instead.
3. Using the system file manager, move or create some files in the "a+b" folder.
4. Notice that Amaze still thinks "a b" contains 0 folders and 0 files.
5. Via Amaze, try to move or create some files in the "a b" folder. You'll get "Operation unsuccessful" or some other error.

**Expected behavior**
Amaze should be opening the "a+b" folder.
-----

This now has a bounty, [here](https://app.bountysource.com/issues/113047886-can-t-open-folders-with-plus-in-the-name).

Please claim after a PR fixing this issue is accepted.
Remember that you can also back the issue adding to the bounty!

**Comment by infinity0** [comment]
Bug exists on Amaze 3.8.2, latest version from F-Droid.

**Comment by infinity0** [comment]
Amaze also cannot delete the folder either, presumably it is trying to delete "a b" instead and failing.

**Comment by EmmanuelMess** [comment]
This now has a bounty, [here](https://app.bountysource.com/issues/113047886-can-t-open-folders-with-plus-in-the-name).

Please claim after a PR fixing this issue is accepted.
Remember that you can also back the issue adding to the bounty!

**Comment by stevealexr** [comment]
It is caused by the url decoder in `getPath()` function in HybridFile.java. Instances of `HybridFile` are created in ListFilesCommand.kt. Then, they are converted to `LayoutElementParcelable` with the path provided by `getPath()` function. The function url decodes the stored path string in `HybridFile` which converts `+` to ` `.

```java
/**
 * Path accessor. Avoid direct access to path since path may have been URL encoded.
 *
 * @return URL decoded path
 */
public String getPath() {
    try {
      return URLDecoder.decode(path, "UTF-8");
    } catch (UnsupportedEncodingException ignored) {
      return path;
    }
}
```
Possible fixes: 
1) Remove the url decoder and ensure the provided path is already decoded in constructor.
2) Expose the stored path string through a method.
