### ISSUE TITLE
Selection of multiple files

### ISSUE THREAD

**Issue by predrag42on** [TeamAmaze/AmazeFileManager#3747]
I can use Amaze to select files for upload (e.g. to Jira from browser), but it only offers to select one file at a time. Other file managers (e.g. default Samsung MyFiles, or XFolder) allow me to select multiple files for upload.
I'd like this feature in Amaze as well.

**Comment by mahi072** [comment]
Hi, I would like to work on this.
Is this issue related to flies on browser or in app, because in app we are able to select multiple files but no upload option present ?

**Comment by mahi072** [comment]
Thanks @VishalNehra, I was able to reproduce the issue.
Can you please also direct me to the exact file in this repository where the changes to be made, if possible?

**Comment by seelchen** [comment]
Hi, it has been a while without a reply from @mahi072. If no one else wants to work on this issue, I would like to work on it.
I have already started investigating a bit and found some places in the code related to this feature request.

* `MainActivityActionMode` is used when multiple files are selected. The floating action button for the feature should probably be added here.
* `MainFragment#returnIntentResults` is the method that returns the selected file to the other application. Currently it only takes one file, so it has to be changed to take multiple files.

I also noticed that in the Google Files app only one file can be selected if the other application only accepts one file. This should probably also be the behavior for the implemented feature.

**Comment by VishalNehra** [comment]
Yea, you're on the right track. Feel free to write in case you need any clarification

**Comment by seelchen** [comment]
Hi, after working with the code I found that there was already an attempt to implement this feature in the [MainActivityActionMode](https://github.com/TeamAmaze/AmazeFileManager/blob/release/4.0/app/src/main/java/com/amaze/filemanager/utils/MainActivityActionMode.kt#L236-L254). 
When multiple files are selected, there is a "Select" button in the dropdown menu which should send all the selected files to the other application. The problem is that the returned `Intent` does not supply the URIs in a `ClipData` ([possible](https://developer.android.com/reference/android/content/Intent#ACTION_SEND_MULTIPLE) since Jelly Bean) so other applications might not find the URIs in the `Intent`.
![image](https://github.com/TeamAmaze/AmazeFileManager/assets/74261221/01dcb7a4-200b-4852-9f8a-efb1d1e71625)

My question is if I should just fix the returned `Intent` of this "Select" button or if I should replace it with a floating action button.
Personally, I think that the option is too hidden in the dropdown menu. There is no indication that a new option was added so users might not find it because they only expect the usual options there.

**Comment by VishalNehra** [comment]
> Hi, after working with the code I found that there was already an attempt to implement this feature in the [MainActivityActionMode](https://github.com/TeamAmaze/AmazeFileManager/blob/release/4.0/app/src/main/java/com/amaze/filemanager/utils/MainActivityActionMode.kt#L236-L254). When multiple files are selected, there is a "Select" button in the dropdown menu which should send all the selected files to the other application. The problem is that the returned `Intent` does not supply the URIs in a `ClipData` ([possible](https://developer.android.com/reference/android/content/Intent#ACTION_SEND_MULTIPLE) since Jelly Bean) so other applications might not find the URIs in the `Intent`. ![image](https://user-images.githubusercontent.com/74261221/280329848-01dcb7a4-200b-4852-9f8a-efb1d1e71625.png)
> 
> My question is if I should just fix the returned `Intent` of this "Select" button or if I should replace it with a floating action button. Personally, I think that the option is too hidden in the dropdown menu. There is no indication that a new option was added so users might not find it because they only expect the usual options there.

Yea, use the FAB, you can use the up arrow or upload icon in Fab for this
