### ISSUE TITLE
Cannot grant SAF permission to Android/data on A11

### ISSUE THREAD

**Issue by GreenGhostForever** [TeamAmaze/AmazeFileManager#3957]
**Describe the bug**

you cannot access any folder inside android / data ( amaze will ask to grant SAF access again but the thing is android folder is not visible in files by google app)

**To Reproduce**

1. open amaze go to android / data / (any folder)
2. app will ask to grant SAF again but android folder is not visible in files by google

**Expected behavior**

1. it's obvious app shouldn't ask SAF again sincd we already granted them before
2. can read any content inside android / data / (any folder)

**Screenshots**

<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/136427398/13a56cd5-e59d-4012-a600-e018565cdddf" height="600" />

<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/136427398/3b74ac39-4591-44d2-8cd0-1aa1dc628725" height="600" />

**Smartphone (please complete the following information):**

 - Device: Realme C21Y 
 - OS: A11 Realme UI 1.0
 - Rooted: no
 - Version: A11

**Additional context**

- fully factory reset done but app still not working
- i try different app to see if this happens to other such app (zarchiver) but it's turned out nope
- i cannot share log no matter how many i try or to where i want to export it won't work obvious 🤦

**Comment by VishnuSanal** [comment]
@GreenGhostForever weird, we chose this approach since this was the only way to access the Android/data folder on A11, IIRC. @TranceLove please confirm.

PS: I use a non-rooted RMX2050 with Android 11 & Realme UI v2.0 & Amaze works fine with Android/data.

**Comment by GreenGhostForever** [comment]
> @GreenGhostForever weird, we chose this approach since this was the only way to access the Android/data folder on A11, IIRC. @TranceLove please confirm.

ikr that's why i wonder what is culprit since only zarchiver can fully access this without requesting for 2nd time i should share log i guess🥴

**Comment by TranceLove** [comment]
@GreenGhostForever Yes please. And I suppose you are using the latest available version?

**Comment by GreenGhostForever** [comment]
> @GreenGhostForever Yes please.
amaze file manager is ask for fighting ig exporting logs to locally or via anything online is not working 🗿

>And I suppose you are using the latest available version?

yes i use latest available

**Comment by GreenMystic** [comment]
damn downgrading documentsui is only way to temporary remedy the problem 

google is truly horsemen of the annoyance 🗿
FFFFFFFFFFFFFFUUUUUUUUUUUUUUUUU
🗿🗿🗿🗿🗿🗿🗿🗿🗿

**Comment by Dret42** [comment]
Same problem for me on Android 12 an no-root device and Amaze 3.10.

**Comment by babloyi** [comment]
![image](https://github.com/user-attachments/assets/3e4dec0d-ce60-420c-8ebe-ad3db0aa3b0a)
I have a rooted device, currently on Android version 14, and I have the same issue:

1. I try accessing a data folder in Android
2. I get the pop-up to grant access, tap OK
3. The device file manager takes me to Android/media instead, and if I backtrack to Android, the data folder is not visible

**Comment by Githubisincomprehensiblegarbage** [comment]
hi,
think i have the same problem. other posters use language that assumes background knowledge i don't have, but it seems like we're experiencing the same problem.
no way to get around it? the "grant SAF access" that forces the google app open seems ineffective. no ideas?
but zarchiver might be able to copy/move the files, then we can access them?

fyi, the reason i seek access is because i am trying to find a free and awesome program to write and research on numerous projects. i don't like obsidian after having no choice but to use it for too long. onenote is okay but, you know, MS is evil.  Trillium looks great! but not on phone :( :( one of the dozens of apps i have tried is Zettel Notes
i think Zettel is hiding my work in this area of the phone. (the developers are creepy about not addressing where the program saves the user's stuff on the user's phone -- not recommended). 
another reason i share the latter is to request advice. any suggestions on how i can catch the stuff i've written in Zettel Notes, move it, and open it in another program? i assume Zettel is using a unique system that other programs may not be able to manage, but i'd like to try. your help would be fantastic. 
thanks!
