### ISSUE TITLE
Range Selection UX Fix (Tap Start & Tap End)

### ISSUE THREAD

**Issue by maltfield** [TeamAmaze/AmazeFileManager#3989]
This is a feature request to change the UX behaviour of the [Range selection](https://github.com/TeamAmaze/AmazeFileManager/issues/2070) feature from an awkward & slow click/drag into tap-first then tap-last to select everything in-between.

## Use Case

A common use-case for "range select" is someone who wants to select all photos taken between two days.

For the purposes of this question, let's assume someone wants to select all photos taken between 01 January 2014 until 31 December 2022. Let's say that's 6,789 photos.

## Range Select (current UX)

Currently it's possible to select multiple items in Amaze, if a user enables ""drag and drop" and sets it to `select items` in the Settings.

After the above change, the UX for selecting a range of files is to click & drag. This is a very, very slow process when trying to select thousands of files. And it "feels" super awkward. Not to mention that it's super counter-intuitive and not documented.

## Range Select (recommended UX)

The UX should be designed such that it's intuitive -- so most users can figure it out without having to read documentation or watch a video, if possible.

Most computer users are familiar with range selection on the desktop where:

1. You click a file
2. You hold the `shift` button on the keyboard
3. You click another file

As a result, every file between the two files clicked is selected. This is a very fast & intuitive UX.

I request that we implement the above UX on mobile as follows:

1. User taps the overflow menu (three dots, top-right) and taps a button titled "range select"
2. User taps on some file
3. User taps on some other file

As a result, the two files clicked and every file in-between them is selected.

## See also

I was requested to create this ticket [here](https://github.com/TeamAmaze/AmazeFileManager/issues/2070#issuecomment-1759352192)

**Comment by VishalNehra** [comment]
This already got implemented in #3972 and is up on play store. 
Select 2 (or multiple) files in list, and tap select fill on the top bar where you see the count of files after selection.

**Comment by HT-7** [comment]
> After the above change, the UX for selecting a range of files is to click & drag. This is a very, very slow process when trying to select thousands of files. And it "feels" super awkward. Not to mention that it's super counter-intuitive and not documented.

Thank you, Michael, for filing this issue.

I am so thankful people with common sense like you exist.

Some people believe "we already have drag to select, so why do we need range selection?"  - to those people: Have fun selecting 5000 files with drag-to-select and then you will realize why **real** range selection is necessary.

Shift range selection is something even Windows 3.1 had three decades ago, yet Google hasn't managed to implement it in their wannabe file manager, even though ES File Explorer had this since at least 2012 (but then Google declared war on third-party file managers with massive restrictions to their operating system).

Desktop computers and laptops had range selection for over 30 years. About time for smartphones to catch up.
