### ISSUE TITLE
feature request: multiline full filename

### ISSUE THREAD

**Issue by crucifyml** [TeamAmaze/AmazeFileManager#496]
cannot figure out witch file I want like this:

![screenshot_20170329-025102](https://cloud.githubusercontent.com/assets/6028985/24421989/a177f17c-13bd-11e7-9f8a-3d287a922217.png)

here is what it is in explorer.

![screenshot_20170329-025636](https://cloud.githubusercontent.com/assets/6028985/24422212/645a2fb6-13be-11e7-95aa-cf0f77b49b87.png)

I think it's better we have a solution for this situation.

**Comment by vishal0071** [comment]
You can view it in properties, right?

**Comment by EmmanuelMess** [comment]
It's ordered, do a binary search, jk. We could change the font size, make the space for the 3 dots smaller or make a configuration to deactivate them at the file level (long press on file would have to yield the same result as the 3 dots).

**Comment by X-Ryl669** [comment]
+1 for being able to change the font size.
Splitting the filename to fit 2 lines or more is the best way IMHO, since there is no compromise, you can see it all.

Else, animating the text (horizontal scrolling based on time) might also work but might look painful to use...

Last solution, since the issue is that all item in the list appear the same so it's impossible to tell the difference without opening them one by one, Amaze could just strip the similar part and show the different, like in this example:

- [DMG][Masam...OP][GB].mp4
- [DMG][Masam...OP][GB].mp4
- [DMG][Masam...OP][GB].mp4

becomes:
- [DMG][Masam...0]...mp4
- [DMG][Masam...1]...mp4
- [DMG][Masam...2]...mp4

It's basically searching for a common prefix in 2 successive list item's text, and make an ellipsis for this prefix, then search for common suffix and make an ellipsis starting from that common suffix too.

**Comment by EmmanuelMess** [comment]
Stripping similar part is a nice idea; on load create a trie, check if the file has a prefix or postfix in that trie and if it doesn't, add it into the trie (as is and reversed), if it does, search for the part that isn't in the trie and show it in with ellipses accordingly.

**Comment by crucifyml** [comment]
@vishal0071 it's not convenient to check every file's properties util you find the file you want to play.
@X-Ryl669 @EmmanuelMess  stripping similar part is nice but that may affect the performance when there are hundreds of episodes and mixed series. however I still wish there would be an option that I can see the full file name when browse the files. 
thank you so much for concerning. sorry for late reply.

**Comment by konkor** [comment]
I think reducing of space around icons, removing this individual property button and hiding extension at least for registered types could help.

**Comment by EmmanuelMess** [comment]
Created [this](https://gist.github.com/EmmanuelMess/aa1f273c819762512c40ffd1d4786f89) that does that for a limited character amount, it needs optimization and is buggy, but is a start. Also, it's in C++11.

**Comment by VishalNehra** [comment]
Working on this by adding a marquee effect. Almost finished.
