### ISSUE TITLE
V3.1.2 RC1 and RC3 smb 'searching for devices' doest find anything

### ISSUE THREAD

**Issue by aguaviva** [TeamAmaze/AmazeFileManager#607]
Other apps do discover the local smb shares

**Comment by ka223** [comment]
The discovery is not working here too.

**Comment by GlassGruber** [comment]
Same thing. 
In my case maybe is because I disabled SMBv1 via [shell](https://support.microsoft.com/en-gb/help/2696547/how-to-enable-and-disable-smbv1-smbv2-and-smbv3-in-windows-and-windows), though other apps like ES Explorer can correctly see the device.
Trying to create manually an SMB anonymous connection I can't connect (no domain filled), I get a connection error on `0.0.0.0<00>/mydeviceip`

**Comment by vishal0071** [comment]
@GlassGruber SMB works fine for manual connection, you shouldn't be getting this error. Make sure you're on latest version of Amaze.

**Comment by GlassGruber** [comment]
Hey @vishal0071 thx for answering this quick! 
Unfortunately I downloaded the last version from F-Droid and it's indeed v. 3.1.2 RC3. I thought it's a correlated issue since I'm experiencing this same problem.  
Do you think I should open another issue for this? 
I don't want to hijack the thread 😛 😄

**Comment by vishal0071** [comment]
@GlassGruber Fdroid is always a bit behind. This issue has already been fixed on RC4, creating an issue will do nothing. Get the updated version for the fix. 
You can get the fdroid compatible version (signed by me, not fdroid) from the link below untill fdroid guys update it there
https://www.androidfilehost.com/?w=files&flid=73985

**Comment by GlassGruber** [comment]
Thank you! I should have checked the release page, thought F-Droid was on par :P
Unfortunately even on RC4 I can't connect same error `Failed to connect: 0.0.0.0<00>/ip.win.device`. Also the device is still not visible after search. 

Any suggestion? The IP I insert is correct, though I leave blank pass user and domain fields, checking the Anonymous box.

**Comment by vishal0071** [comment]
Try clearing app data from System settings and recreating the connection

**Comment by GlassGruber** [comment]
No dice :( 
Even uninstalled reinstalled. 
Maybe this can give more info, but the SMB profile is deleted automatically after a short time, don't know why.

**Comment by GlassGruber** [comment]
Hey there small update, I've tested with my devices re-enabling the SMB1 protocol and works without problem (though still not shown in the search dialog). I've updated this protocol issue on #670 
Thank you for your time! ;)
