### ISSUE TITLE
Memory consumption in Android 6.0.1 device 

### ISSUE THREAD

**Issue by Jo2joe** [TeamAmaze/AmazeFileManager#626]
Good day Vishal Nehra. 

This is Joe Oh from PointMobile. 

Our team inform me memory leak issue in 3.1.2RC1 and RC3

When app just run 
![memory1](https://cloud.githubusercontent.com/assets/29136641/26769936/c7c449b4-49ed-11e7-862b-585245fa4159.png)

When I copy two screenshots from /Pictures/Screenshots to other folder
![memory2](https://cloud.githubusercontent.com/assets/29136641/26769952/e7581120-49ed-11e7-8ec4-65b2dbe76324.png)

and then I close the Amaze File manager by Android's recent apps list 
![mormory3](https://cloud.githubusercontent.com/assets/29136641/26769971/0afff94e-49ee-11e7-8f81-81fe04bb3c15.png)

Could you give your comment of this? Is this amount of memory consumption expected?

**Comment by EmmanuelMess** [comment]
Sorry, I can't read any useful info from here, would you point out the concerning data?

**Comment by vishal0071** [comment]
All the streams and channels are closed regardless of any error. And all the variables are GCd by JVM automatically. If you could point of the source of leak maybe we can clean it up in finalize method otherwise everything should be good.
Also it's pretty normal for memory usage to go a bit high when performing such operation.

**Comment by EmmanuelMess** [comment]
With no answer in a few months I'm closing this.
