### ISSUE TITLE
History order is inverted, newest is last

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#831]
The last elements is the last folder visited, contrary to normal history were first is last action done (think of your browser, first page is last visited).

**Comment by AnirudhaAgashe** [comment]
This can be fixed by either running the loop in method toHybridFileArrayList in FileUtils class in reverse order or you can call Collection.reverse before returning the list.

**Comment by EmmanuelMess** [comment]
That is not optimal (a stack would be better), also I've noticed that it is not restoring the history from database. This will take a few days to fix.

**Comment by AnirudhaAgashe** [comment]
I checked the implementation there is no provision to load History from database.  
Loading history from database is done for Recents tab.
Currently an array is used to keep track of the history which is in-memory implementation. It would get cleared on exit. I am not sure how stack would help since the elements are inserted in the order in which they were visited so in effect what we want is the reverse of this array. Am I missing anything ?

**Comment by EmmanuelMess** [comment]
`UtilsHandler.getPath(Operation.HISTORY)` seems as it reads the history from DB (it is used for "Recents" in navigation drawer).
You are missing how the [stack](https://en.wikipedia.org/wiki/Stack_(abstract_data_type)#/media/File:Lifo_stack.png) works, it's O(1) to add an element to the front (as opposed to O(n) in List) and it's O(n) to read all elements (get(i) = O(1) because of underlying array implementation).

**Comment by AnirudhaAgashe** [comment]
Ok. I thought when you said History you were referring to the "History" in the overflow menu. Order of elements in "History" also have same behavior as that of "Recent" tab. So you may consider changing that as well to keep consistent application behavior

![device-2017-11-22-185045](https://user-images.githubusercontent.com/3098180/33130007-e4d912c8-cfb7-11e7-8870-b88153274f87.png)

**Comment by EmmanuelMess** [comment]
Yes I was refering to that.
