### ISSUE TITLE
BLACK for AMOLED doesn't change FAB's color

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#886]

**Comment by VishalNehra** [comment]
FAB color isn't supposed to change for dark themes.

**Comment by EmmanuelMess** [comment]
I think before the library change the color changed with the theme; but I know after the lib change it does. 
This is a bug either way. It really doesn't look good with the labels always black.

**Comment by VishalNehra** [comment]
No it didn't. If you think there should be something that should change then  come up with a possible solution too..

**Comment by EmmanuelMess** [comment]
The bug would be here:
https://github.com/TeamAmaze/AmazeFileManager/blob/8a956c516843aeb4c5dee3d251997b29abd49784/app/src/play/java/com/amaze/filemanager/activities/MainActivity.java#L1837-L1840
I think it would be better to change fab color with theme.

**Comment by PiwwowPants** [comment]
I see now I missed that part when adding this. It just defaults the black theme to use the light theme fab option label background and text.

The entire black theme reverts to the dark theme when the fab is opened. If you cared enough, you'd need a different "fabBgView" resource that tints the black a little less so changing those labels to have a black background wouldn't cause the label to fade into the black background. Essentially, I just didn't finish it.
Otherwise, just adding AppTheme.BLACK to that conditional would fix it and retain the dark behavior.

I would but if I make any change to the play version's MainActivity revolving around this I just start getting color errors. So you're on your own on that one.

**Comment by EmmanuelMess** [comment]
Fixed in #1140
