### ISSUE TITLE
Chainfire's How-To SU repo is a library in our app

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#969]
[LibSuperUser](https://github.com/Chainfire/libsuperuser) should only be an example of usage, why is the code added to our app?

**Comment by VishalNehra** [comment]
What do you mean?

**Comment by TranceLove** [comment]
`MainActivity` has actual usage of `eu.chainfire.libsuperuser.Shell`.

**Comment by EmmanuelMess** [comment]
Should they? That's my question…

**Comment by Alexander--** [comment]
Chainfire himself calls it "an example of usage", but most people just use libsuperuser as a complete solution, — it has limited features, but is quite good at what little it can do.

**Comment by veniosg** [comment]
Given that he has an [example of how to use the library](https://github.com/Chainfire/libsuperuser/tree/master/libsuperuser_example) and the breadth of pitfalls it avoids, I'd interpret the 
_Example code for "How-To SU"_ line to mean that this is how SU should be used, meaning it's actually intended to be used as a library rather than an example (like how TrivialDrive v1 and IAP were promoted).

**Comment by EmmanuelMess** [comment]
Very well, it's a library then, closed.
