### ISSUE TITLE
commons-logging defines classes that conflict with classes now provided by Android

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [TeamAmaze/AmazeFileManager#974]
Error:(158) Error: commons-logging defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]

**Comment by TranceLove** [comment]
Studying the library dependencies it turned out (currently) the culprit is `junrar`.

```
+--- com.github.junrar:junrar:0.7
|    +--- commons-logging:commons-logging-api:1.1 -> commons-logging:commons-logging:1.1.1
|    \--- org.apache.commons:commons-vfs2:2.0
|         +--- org.apache.maven.scm:maven-scm-api:1.4
|         |    \--- org.codehaus.plexus:plexus-utils:1.5.6
|         \--- org.apache.maven.scm:maven-scm-provider-svnexe:1.4
|              +--- org.apache.maven.scm:maven-scm-provider-svn-commons:1.4
|              |    +--- org.apache.maven.scm:maven-scm-api:1.4 (*)
|              |    \--- org.codehaus.plexus:plexus-utils:1.5.6
|              +--- regexp:regexp:1.3
|              +--- org.apache.maven.scm:maven-scm-api:1.4 (*)
|              \--- org.codehaus.plexus:plexus-utils:1.5.6
```

But I wonder if we still need `maven-scm-api` and `maven-scm-provider-svnexe` which is transitive dependencies of `commons-vfs`?

Unluckily junrar was still depends on commons-vfs 2.0, which [2.1 fixed this redundant dependency](https://issues.apache.org/jira/browse/VFS-395), so I think I'll need to exclude this manually.

Will hand in a PR after some further testing.

**Comment by VishalNehra** [comment]
Switching to latest v1.2 of this library fixes this issue.
